pokemon_move_names = [
        "Zippy Zap", "Zing Zap", "Zen Headbutt", "Zap Cannon", "Yawn", "X-Scissor",
        "Wring Out", "Wrap", "Worry Seed", "Work Up", "Wood Hammer", "Wonder Room",
        "Withdraw", "Wish", "Wing Attack", "Will-O-Wisp", "Wildbolt Storm",
        "Wild Charge", "Wide Guard", "Wicked Torque", "Wicked Blow", "Whirlwind",
        "Whirlpool", "Weather Ball", "Wave Crash", "Waterfall", "Water Spout",
        "Water Sport", "Water Shuriken", "Water Pulse", "Water Pledge", "Water Gun",
        "Wake-Up Slap", "Volt Tackle", "Volt Switch", "Vital Throw", "Vise Grip",
        "Vine Whip", "Victory Dance", "Venoshock", "Venom Drench", "Veevee Volley",
        "Vacuum Wave", "V-create", "Uproar", "Upper Hand", "U-turn", "Twister",
        "Twinkle Tackle", "Twineedle", "Twin Beam", "Trump Card", "Trop Kick",
        "Triple Kick", "Triple Dive", "Triple Axel", "Triple Arrows", "Trick-or-Treat",
        "Trick Room", "Trick", "Tri Attack", "Transform", "Trailblaze", "Toxic Thread",
        "Toxic Spikes", "Toxic", "Torment", "Torch Song", "Topsy-Turvy", "Tidy Up",
        "Tickle", "Thunderous Kick", "Thunderclap", "Thunderbolt", "Thunder Wave",
        "Thunder Shock", "Thunder Punch", "Thunder Fang", "Thunder Cage", "Thunder",
        "Throat Chop", "Thrash", "Thousand Waves", "Thousand Arrows", "Thief",
        "Terrain Pulse", "Tera Starstorm", "Tera Blast", "Temper Flare", "Teleport",
        "Telekinesis", "Teeter Dance", "Tectonic Rage", "Techno Blast", "Teatime",
        "Tearful Look", "Taunt", "Tar Shot", "Take Heart", "Take Down", "Tailwind",
        "Tail Whip", "Tail Slap", "Tail Glow", "Tackle", "Tachyon Cutter", "Syrup Bomb",
        "Synthesis", "Synchronoise", "Swords Dance", "Switcheroo", "Swift",
        "Sweet Scent", "Sweet Kiss", "Swallow", "Swagger", "Surging Strikes", "Surf",
        "Supersonic Skystrike", "Supersonic", "Superpower", "Supercell Slam",
        "Super Fang", "Sunsteel Strike", "Sunny Day", "Sucker Punch", "Subzero Slammer",
        "Substitute", "Submission", "Stun Spore", "Stuff Cheeks", "Struggle Bug",
        "Struggle", "String Shot", "Strength Sap", "Strength", "Strange Steam",
        "Storm Throw", "Stored Power", "Stone Edge", "Stone Axe", "Stomping Tantrum",
        "Stomp", "Stoked Sparksurfer", "Stockpile", "Sticky Web", "Steel Wing",
        "Steel Roller", "Steel Beam", "Steamroller", "Steam Eruption", "Stealth Rock",
        "Springtide Storm", "Spotlight", "Spore", "Splishy Splash",
        "Splintered Stormshards", "Splash", "Spite", "Spit Up", "Spirit Shackle",
        "Spirit Break", "Spin Out", "Spiky Shield", "Spikes", "Spike Cannon",
        "Spider Web", "Spicy Extract", "Speed Swap", "Spectral Thief", "Sparkly Swirl",
        "Sparkling Aria", "Spark", "Spacial Rend", "Soul-Stealing 7-Star Strike",
        "Sonic Boom", "Solar Blade", "Solar Beam", "Soft-Boiled", "Soak", "Snowscape",
        "Snore", "Snipe Shot", "Snatch", "Snarl", "Snap Trap", "Smokescreen", "Smog",
        "Smelling Salts", "Smart Strike", "Smack Down", "Sludge Wave", "Sludge Bomb",
        "Sludge", "Sleep Talk", "Sleep Powder", "Slash", "Slam", "Slack Off",
        "Sky Uppercut", "Sky Drop", "Sky Attack", "Skull Bash", "Skitter Smack",
        "Skill Swap", "Sketch", "Sizzly Slide", "Sinister Arrow Raid", "Sing",
        "Simple Beam", "Silver Wind", "Silk Trap", "Signal Beam", "Shore Up",
        "Shock Wave", "Shift Gear", "Shelter", "Shell Trap", "Shell Smash",
        "Shell Side Arm", "Sheer Cold", "Shed Tail", "Shattered Psyche", "Sharpen",
        "Shadow Sneak", "Shadow Punch", "Shadow Force", "Shadow Claw", "Shadow Bone",
        "Shadow Ball", "Self-Destruct", "Seismic Toss", "Seed Flare", "Seed Bomb",
        "Secret Sword", "Secret Power", "Searing Sunraze Smash", "Searing Shot",
        "Screech", "Scratch", "Scorching Sands", "Scary Face", "Scale Shot", "Scald",
        "Savage Spin-Out", "Sappy Seed", "Sandstorm", "Sandsear Storm", "Sand Tomb",
        "Sand Attack", "Salt Cure", "Safeguard", "Sacred Sword", "Sacred Fire",
        "Ruination", "Round", "Rototiller", "Roost", "Rollout", "Rolling Kick",
        "Role Play", "Rock Wrecker", "Rock Tomb", "Rock Throw", "Rock Smash",
        "Rock Slide", "Rock Polish", "Rock Climb", "Rock Blast", "Roar of Time",
        "Roar", "Rising Voltage", "Revival Blessing", "Reversal", "Revenge",
        "Revelation Dance", "Return", "Retaliate", "Rest", "Relic Song", "Refresh",
        "Reflect Type", "Reflect", "Recycle", "Recover", "Razor Wind", "Razor Shell",
        "Razor Leaf", "Rapid Spin", "Rain Dance", "Raging Fury", "Raging Bull",
        "Rage Powder", "Rage Fist", "Rage", "Quiver Dance", "Quick Guard",
        "Quick Attack", "Quash", "Pyro Ball", "Pursuit", "Purify", "Punishment",
        "Pulverizing Pancake", "Psywave", "Psystrike", "Psyshock", "Psyshield Bash",
        "Psycho Shift", "Psycho Cut", "Psycho Boost", "Psychic Terrain", "Psychic Noise",
        "Psychic Fangs", "Psychic", "Psych Up", "Psyblade", "Psybeam", "Protect",
        "Prismatic Laser", "Present", "Precipice Blades", "Power-Up Punch",
        "Power Whip", "Power Trip", "Power Trick", "Power Swap", "Power Split",
        "Power Shift", "Power Gem", "Powder Snow", "Powder", "Pound", "Pounce",
        "Population Bomb", "Poltergeist", "Pollen Puff", "Poison Tail", "Poison Sting",
        "Poison Powder", "Poison Jab", "Poison Gas", "Poison Fang", "Pluck", "Play Rough",
        "Play Nice", "Plasma Fists", "Pin Missile", "Pika Papow", "Photon Geyser",
        "Phantom Force", "Petal Dance", "Petal Blizzard", "Perish Song", "Peck",
        "Payback", "Pay Day", "Parting Shot", "Parabolic Charge", "Pain Split",
        "Overheat", "Overdrive", "Outrage", "Origin Pulse", "Order Up", "Ominous Wind",
        "Odor Sleuth", "Octolock", "Octazooka", "Oceanic Operetta", "Obstruct",
        "Oblivion Wing", "Nuzzle", "Noxious Torque", "Noble Roar", "No Retreat",
        "Nightmare", "Night Slash", "Night Shade", "Night Daze", "Never-Ending Nightmare",
        "Needle Arm", "Nature's Madness", "Nature Power", "Natural Gift", "Nasty Plot",
        "Mystical Power", "Mystical Fire", "Multi-Attack", "Muddy Water", "Mud-Slap",
        "Mud Sport", "Mud Shot", "Mud Bomb", "Mountain Gale", "Mortal Spin",
        "Morning Sun", "Moonlight", "Moongeist Beam", "Moonblast", "Misty Terrain",
        "Misty Explosion", "Mist Ball", "Mist", "Mirror Shot", "Mirror Move",
        "Mirror Coat", "Miracle Eye", "Minimize", "Mind Reader", "Mind Blown",
        "Mimic", "Milk Drink", "Mighty Cleave", "Metronome", "Meteor Mash",
        "Meteor Beam", "Meteor Assault", "Metal Sound", "Metal Claw", "Metal Burst",
        "Menacing Moonraze Maelstrom", "Memento", "Megahorn", "Mega Punch", "Mega Kick",
        "Mega Drain", "Meditate", "Mean Look", "Me First", "Max Wyrmwind", "Max Strike",
        "Max Steelspike", "Max Starfall", "Max Rockfall", "Max Quake", "Max Phantasm",
        "Max Overgrowth", "Max Ooze", "Max Mindstorm", "Max Lightning", "Max Knuckle",
        "Max Hailstorm", "Max Guard", "Max Geyser", "Max Flutterby", "Max Flare",
        "Max Darkness", "Max Airstream", "Matcha Gotcha", "Mat Block", "Malignant Chain",
        "Malicious Moonsault", "Make It Rain", "Magnitude", "Magnetic Flux",
        "Magnet Rise", "Magnet Bomb", "Magma Storm", "Magical Torque", "Magical Leaf",
        "Magic Room", "Magic Powder", "Magic Coat", "Mach Punch", "Luster Purge",
        "Lunge", "Lunar Dance", "Lunar Blessing", "Lumina Crash", "Lucky Chant",
        "Low Sweep", "Low Kick", "Lovely Kiss", "Lock-On", "Liquidation",
        "Light That Burns the Sky", "Light Screen", "Light of Ruin", "Life Dew",
        "Lick", "Let's Snuggle Forever", "Leer", "Leech Seed", "Leech Life", "Leafage",
        "Leaf Tornado", "Leaf Storm", "Leaf Blade", "Lava Plume", "Last Respects",
        "Last Resort", "Lash Out", "Laser Focus", "Land's Wrath", "Kowtow Cleave",
        "Knock Off", "King's Shield", "Kinesis", "Karate Chop", "Jungle Healing",
        "Jump Kick", "Judgment", "Jet Punch", "Jaw Lock", "Ivy Cudgel", "Iron Tail",
        "Iron Head", "Iron Defense", "Ion Deluge", "Instruct", "Ingrain", "Infestation",
        "Inferno Overdrive", "Inferno", "Infernal Parade", "Incinerate", "Imprison",
        "Icy Wind", "Icicle Spear", "Icicle Crash", "Ice Spinner", "Ice Shard",
        "Ice Punch", "Ice Hammer", "Ice Fang", "Ice Burn", "Ice Beam", "Ice Ball",
        "Hypnosis", "Hyperspace Hole", "Hyperspace Fury", "Hyper Voice", "Hyper Fang",
        "Hyper Drill", "Hyper Beam", "Hydro Vortex", "Hydro Steam", "Hydro Pump",
        "Hydro Cannon", "Hurricane", "Howl", "Horn Leech", "Horn Drill", "Horn Attack",
        "Hone Claws", "Hold Hands", "Hold Back", "High Jump Kick", "High Horsepower",
        "Hidden Power", "Hex", "Helping Hand", "Heavy Slam", "Heat Wave", "Heat Crash",
        "Heart Swap", "Heart Stamp", "Healing Wish", "Heal Pulse", "Heal Order",
        "Heal Block", "Heal Bell", "Headlong Rush", "Headbutt", "Head Smash",
        "Head Charge", "Haze", "Harden", "Hard Press", "Happy Hour", "Hammer Arm",
        "Hail", "Gyro Ball", "Gust", "Gunk Shot", "Guillotine", "Guardian of Alola",
        "Guard Swap", "Guard Split", "Grudge", "Growth", "Growl", "Gravity", "Grav Apple",
        "Grassy Terrain", "Grassy Glide", "Grass Whistle", "Grass Pledge", "Grass Knot",
        "Glitzy Glow", "Glare", "Glaive Rush", "Glaciate", "Glacial Lance",
        "Gigavolt Havoc", "Gigaton Hammer", "Giga Impact", "Giga Drain", "Geomancy",
        "Genesis Supernova", "Gear Up", "Gear Grind", "Gastro Acid", "Future Sight",
        "Fusion Flare", "Fusion Bolt", "Fury Swipes", "Fury Cutter", "Fury Attack",
        "Frustration", "Frost Breath", "Frenzy Plant", "Freezy Frost", "Freezing Glare",
        "Freeze-Dry", "Freeze Shock", "Foul Play", "Forest's Curse", "Foresight",
        "Force Palm", "Follow Me", "Focus Punch", "Focus Energy", "Focus Blast",
        "Flying Press", "Fly", "Flower Trick", "Flower Shield", "Floral Healing",
        "Floaty Fall", "Flip Turn", "Fling", "Fleur Cannon", "Flatter", "Flash Cannon",
        "Flash", "Flare Blitz", "Flamethrower", "Flame Wheel", "Flame Charge",
        "Flame Burst", "Flail", "Fissure", "Fishious Rend", "First Impression",
        "Fire Spin", "Fire Punch", "Fire Pledge", "Fire Lash", "Fire Fang", "Fire Blast",
        "Final Gambit", "Fillet Away", "Fiery Wrath", "Fiery Dance", "Fickle Beam",
        "Fell Stinger", "Feint Attack", "Feint", "Feather Dance", "False Swipe",
        "False Surrender", "Fake Tears", "Fake Out", "Fairy Wind", "Fairy Lock",
        "Facade", "Extreme Speed", "Extreme Evoboost", "Extrasensory", "Explosion",
        "Expanding Force", "Eternabeam", "Esper Wing", "Eruption", "Entrainment",
        "Energy Ball", "Endure", "Endeavor", "Encore", "Ember", "Embargo", "Electroweb",
        "Electro Shot", "Electro Drift", "Electro Ball", "Electrify", "Electric Terrain",
        "Egg Bomb", "Eerie Spell", "Eerie Impulse", "Echoed Voice", "Earthquake",
        "Earth Power", "Dynamic Punch", "Dynamax Cannon", "Dual Wingbeat", "Dual Chop",
        "Drum Beating", "Drill Run", "Drill Peck", "Dream Eater", "Draining Kiss",
        "Drain Punch", "Dragon Tail", "Dragon Rush", "Dragon Rage", "Dragon Pulse",
        "Dragon Hammer", "Dragon Energy", "Dragon Darts", "Dragon Dance", "Dragon Claw",
        "Dragon Cheer", "Dragon Breath", "Dragon Ascent", "Draco Meteor", "Double-Edge",
        "Double Team", "Double Slap", "Double Shock", "Double Kick", "Double Iron Bash",
        "Double Hit", "Doom Desire", "Doodle", "Dizzy Punch", "Dive", "Discharge",
        "Disarming Voice", "Disable", "Dire Claw", "Dig", "Diamond Storm",
        "Devastating Drake", "Detect", "Destiny Bond", "Defog", "Defense Curl",
        "Defend Order", "Decorate", "Dazzling Gleam", "Darkest Lariat", "Dark Void",
        "Dark Pulse", "Cut", "Curse", "Crush Grip", "Crush Claw", "Crunch", "Cross Poison",
        "Cross Chop", "Crafty Shield", "Crabhammer", "Covet", "Court Change", "Counter",
        "Cotton Spore", "Cotton Guard", "Cosmic Power", "Corrosive Gas", "Corkscrew Crash",
        "Core Enforcer", "Copycat", "Conversion 2", "Conversion", "Continental Crush",
        "Constrict", "Confusion", "Confuse Ray", "Confide", "Comeuppance", "Comet Punch",
        "Combat Torque", "Collision Course", "Coil", "Coaching", "Close Combat",
        "Clear Smog", "Clangorous Soulblaze", "Clangorous Soul", "Clanging Scales",
        "Clamp", "Circle Throw", "Chloroblast", "Chip Away", "Chilly Reception",
        "Chilling Water", "Chatter", "Charm", "Charge Beam", "Charge", "Celebrate",
        "Ceaseless Edge", "Catastropika", "Captivate", "Camouflage", "Calm Mind",
        "Buzzy Buzz", "Burning Jealousy", "Burning Bulwark", "Burn Up", "Bullet Seed",
        "Bullet Punch", "Bulldoze", "Bulk Up", "Bug Buzz", "Bug Bite", "Bubble Beam",
        "Bubble", "Brutal Swing", "Brine", "Brick Break", "Breakneck Blitz",
        "Breaking Swipe", "Brave Bird", "Branch Poke", "Bouncy Bubble", "Bounce",
        "Boomburst", "Bonemerang", "Bone Rush", "Bone Club", "Bolt Strike", "Bolt Beak",
        "Body Slam", "Body Press", "Blue Flare", "Bloom Doom", "Blood Moon", "Block",
        "Blizzard", "Bleakwind Storm", "Blazing Torque", "Blaze Kick", "Blast Burn",
        "Black Hole Eclipse", "Bitter Malice", "Bitter Blade", "Bite", "Bind", "Bide",
        "Bestow", "Belly Drum", "Belch", "Behemoth Blade", "Behemoth Bash", "Beat Up","Beak Blast", "Baton Pass", "Barrier", "Barrage", "Barb Barrage", "Baneful Bunker",
        "Baddy Bad", "Baby-Doll Eyes", "Axe Kick", "Avalanche", "Autotomize", "Aurora Veil",
        "Aurora Beam", "Aura Wheel", "Aura Sphere", "Attract", "Attack Order", "Astral Barrage",
        "Astonish", "Assurance", "Assist", "Aromatic Mist", "Aromatherapy", "Armor Cannon",
        "Arm Thrust", "Aqua Tail", "Aqua Step", "Aqua Ring", "Aqua Jet", "Aqua Cutter",
        "Apple Acid", "Ancient Power", "Anchor Shot", "Amnesia", "Ally Switch", "Alluring Voice",
        "All-Out Pummeling", "Air Slash", "Air Cutter", "Agility", "After You", "Aeroblast",
        "Aerial Ace", "Acupressure", "Acrobatics", "Acid Spray", "Acid Downpour", "Acid Armor",
        "Acid", "Accelerock", "Absorb", "10,000,000 Volt Thunderbolt",
    ]